### PR TITLE
Update jQuery UI and postcss-cssnext per security alerts (SCP-3893)

### PR DESCRIPTION
**Pull request by eweitz**
This fixes reported security vulnerabilities in [jQuery](https://github.com/broadinstitute/single_cell_portal_core/security/dependabot/yarn.lock/jquery-ui/open) and [`postcss-cssnext`](https://github.com/broadinstitute/single_cell_portal_core/security/dependabot/yarn.lock/color-string/open).  The latter is technically unused in production, but seems relatively straightforward to update -- unlike `@rails/webpacker` and `react-scripts@3.4.4`.

It upgrades jQuery one minor version, from 1.12 to [1.13](https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released/).  It also migrates away from the [deprecated `postcss-cssnext` package](https://www.npmjs.com/package/postcss-cssnext) to [a slightly more modern approach for Webpacker 5](https://candland.net/2021/upgrading-rails-webpacker-tailwindcss/) (sans e.g. Tailwind).

To test:
* Update dependencies, `yarn install --force`
* Go to a Study
* Go to Settings tab
* Change date in datepicker
* Save, refresh
* Verify the date you entered persists
* Verify that visual styling seems unchanged
* Search 3 genes (e.g.  [in "Tuberculosis in human female lymph"](https://singlecell-staging.broadinstitute.org/single_cell/study/SCP282/tuberculosis-in-human-female-lymph?genes=ABL1%2CADCY5%2CAGPAT2#study-visualize))
* Click around in Morpheus dot plot, including its menu
* Verify that UI and widget look OK

This satisfies SCP-3893.

### CODE REVIEW

**Review by devonbush — APPROVED** [review]
confirmed it works for me
that is some arcane environment.js config--thanks for the helpful comment

**Review by bistline — APPROVED** [review]
Works, but I noticed something strange in the console when checking the jquery-ui version:
```
>  $.ui.version
<- '1.12.1'
```

**Comment by eweitz** [comment]
Per Jon's note, I looked deeper and found that jQuery UI is pulled in not only via `package.json`, but also by our legacy JS requirement mechanism.  I'm wading through that thicket now to see how we can update to jQuery UI 1.13 there as well.

**Comment by eweitz** [comment]
Great find, @bistline.  That's updated now.

It turns out Morpheus exposes its jQuery UI globally.  And as we've known, it requires having a vendored copy of the raw dependency source among our files.  So updating SCP's global jQuery UI required manually [building Morpheus's custom jQuery UI download](https://jqueryui.com/download/#!version=1.13.0&components=111111011111101010111101110000000000000000000000), and patching that into its dependencies.

That's a problem for security and speed, so I outlined a [Morpheus modernization proposal](https://docs.google.com/document/d/11eNlwMjwKoUcx4TQflzxw4DuN9q03fNNLphUuAVNIc4/edit#heading=h.4zcyofksooer) for engineering strategy.

**Pull request merged**
