### PR TITLE
Release 1.38.0

### PR DESCRIPTION
**Pull request by eweitz**

### CODE REVIEW

**Comment by bistline** [comment]
FWIW I saw the [exact same failures](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/4356427939/jobs/7614420752) a little while ago.  Locally the same tests don't fail so I'm guessing this is transient but our overall build stability is poor right now which is troubling.

**Review by ehanna4 — APPROVED** [review]

**Review by jlchang — APPROVED** [review]

**Review by bistline — APPROVED** [review]

**Comment by eweitz** [comment]
Per above note, the [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/4356427939/jobs/7614420752#step:7:4573) seems like a false positive.

```
### FAILURES and ERRORS ###
*** Yarn test failures ***

*** Rails test failures ***

  ExternalResourcesControllerTest#test_should_create_then_update_then_delete_external_resource [/home/app/webapp/test/api/external_resources_controller_test.rb:72]:
  Expected response to be a <2XX: success>, but was a <503: Service Unavailable>

  StudyValidationTest#test_should_disable_downloads_for_reviewers:
  RuntimeError: not a redirect! 200 OK
Exiting with code: 1
Error: Process completed with exit code 1.
```

I just started another build to ensure it's not consistently reproducible.

**Comment by eweitz** [comment]
The [build failed](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/4356427939/jobs/7633523585#step:7:4594) again, due to seemingly similar (but not the same) causes.  Given the failure is quite consistently reproducible, this seems like a false positive.

```
### FAILURES and ERRORS ###
*** Yarn test failures ***

*** Rails test failures ***

  FireCloudClientTest#test_manage_workspace_configurations:
  RuntimeError: Wrapped undumpable exception for: RuntimeError: Duplicate entry 'single-cell-portal-test-test_manage_workspace_configurations-a05' for key 'IDX_WS_UNIQUE_NAMESPACE_NAME'

  StudyValidationTest#test_should_disable_downloads_for_reviewers:
  NoMethodError: undefined method `study_shares' for nil:NilClass

  StudyValidationTest#test_should_fail_all_ingest_pipeline_parse_jobs [/home/app/webapp/test/integration/study_validation_test.rb:56]:
  Study did not successfully save

  StudyValidationTest#test_should_enforce_access_restrictions_on_editing_studies [/home/app/webapp/test/integration/study_validation_test.rb:363]:
  Expected true to be nil or false

  StudyValidationTest#test_should_prevent_changing_firecloud_attributes [/home/app/webapp/test/integration/study_validation_test.rb:159]:
  Did not redirect to upload successfully.

  StudySharesControllerTest#test_should_create_then_update_then_delete_study_share [/home/app/webapp/test/api/study_shares_controller_test.rb:78]:
  Did not successfully delete study file, expected response of 204 but found 503.
Exiting with code: 1
Error: Process completed with exit code 1.
```

**Comment by eweitz** [comment]
Jon agreed these failures with false positives insofar as SCP code is concerned, so I'll merge.

**Pull request merged**
