### PR TITLE
Mark legacy AnnData files as reference, enforce metadata convention (SCP-4928, SCP-5042)

### PR DESCRIPTION
**Pull request by bistline**
#### BACKGROUND & CHANGES
This update marks all previously uploaded AnnData files as "reference" files, meaning they will not be parsed, even if the user has their `ingest_anndata_file` feature flag set to `true`.  In addition, all AnnData files that are parsed will now have the metadata convention enforced.  Lastly, this fixes a new bug that caused all uploaded AnnData files in "classic" mode to be parsed, when they should not have.

#### MANUAL TESTING
1. Boot as normal, start Delayed::Job and sign in
2. Go to any study that is not in the "AnnData" mode and upload any `.h5ad` file as a reference file
3. Confirm it pushes to the bucket and does not attempt to parse.  Note: you will still see an ingest job, but the `--extract` parameter will not be present, and legacy behavior of simply opening the file and validating that it is readable is applied

### CODE REVIEW

**Comment by bistline** [comment]
Same `IDX_WS_UNIQUE_NAMESPACE_NAME` error.

**Review by ehanna4 — APPROVED** [review]
Works as advertised - was able to upload a "reference anndata file" in classic mode and it saved without extraction

**Review by jlchang — APPROVED** [review]
Functional review: confirmed that when uploading `.h5ad` file to a "classic mode" study, the `--extract` parameter is not sent to `ingest_pipeline.py` and the file is checked for open-ability and available for download.

**Comment by eweitz** [comment]
Details on the [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/4547366636/jobs/8017157124#step:7:4584) that caused this false positive:

```
### FAILURES and ERRORS ###
*** Yarn test failures ***

*** Rails test failures ***

  StudyCleanupToolsTest#before_all:
  Mongoid::Errors::Validations: 
Exiting with code: 1
```

Jean and I are looking into the cause of other build failures.  Log search isn't available for GitHub Actions, so making the causative error searchable by putting it in a PR comment seems like a decent workaround for assessing build failures across PRs.

**Pull request merged**
