### PR TITLE
Missed some cleanup of reference images

### PR DESCRIPTION
**Pull request by ehanna4**
Missed some files around reference images which is why staging is currently broken
This finds and removes those remaining pieces

Utilized: https://github.com/broadinstitute/single_cell_portal_core/commit/f8b4cdc3bc8e9372947d01a8333c90ac2c151f79#diff-ff4757fbd05349b697a855bde79438e30252a0df7191de9205c1a4d7d46a16a9 for context to find the rest

To test
- pull this branch and go to any study explore page
- confirm page loads no errors

### CODE REVIEW

**Review by eweitz — APPROVED** [review]
Code looks good!  

Between this and #1786, removing this unused feature removes almost 400 lines of code.  That notably helps maintainability.

**Review by michelle-vel — APPROVED** [review]
looks good and much cleaner!

**Comment by eweitz** [comment]
The [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/5149450968/jobs/9272463775?pr=1788#step:7:4451) looks like a false positive:

```
### FAILURES and ERRORS ###
*** Yarn test failures ***

*** Rails test failures ***

  FireCloudClientTest#test_get_workspace_files:
  RuntimeError: Wrapped undumpable exception for: RuntimeError: Duplicate entry 'single-cell-portal-test-test_get_workspace_files-9583e614-e1b4-4' for key 'IDX_WS_UNIQUE_NAMESPACE_NAME'
Exiting with code: 1
Error: Process completed with exit code 1.
```

This is the first failure due to `IDX_WS_UNIQUE_NAMESPACE_NAME` recorded in a PR since it was [mitigated](https://github.com/broadinstitute/single_cell_portal_core/pull/1766) on May 9.  The [most recent recorded case of this failure](https://github.com/search?q=repo%3Abroadinstitute%2Fsingle_cell_portal_core+IDX_WS_UNIQUE_NAMESPACE_NAME&type=pullrequests) was March 27.

I'll re-run CI now to confirm this was a false positive.

**Comment by eweitz** [comment]
The [build failed](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/5149450968/jobs/9291763360?pr=1788#step:7:4355) again, with a different false positive:

```
*** Rails test failures ***

  HcaAzulClientTest#test_should_get_all_projects_without_error:
  RuntimeError: Wrapped undumpable exception for: RestClient::BadGateway: 502 Bad Gateway
Exiting with code: 1
Error: Process completed with exit code 1.
```

Per yesterday's [note](https://broadinstitute.slack.com/archives/CBEHTH601/p1685655415652639), I'll merge this now.

**Pull request merged**
