### PR TITLE
Improving test reliability/stability (SCP-3168, SCP-3138)

### PR DESCRIPTION
**Pull request by bistline**
Attempting to improve both the reliability and stability of test runs in Travis.  Changes so far:

1. Using block form of `File.open()` where appropriate to ensure no dangling file handlers are left open
2. Use `String#encode!` instead of `String#encode` to force return
3. Invoke tests with `bin/rails test` instead of `bundle exec bin/rake test`
4. Force CI runs in Travis to use full VM config (this is the default, but ensuring it doesn't hurt)

5 consecutive (discounting failures due to `mimemagic` issues, which marked some commits as "failed") clean builds were observed.   While this is not completely indicative that all issues have been permanently resolved, given the previous failure rate of ~85%, this seems like a good enough first start.  Additional enhancements/individual test fixes may be necessary in the future.

This PR satisfies SCP-3168 and SCP-3138.

### CODE REVIEW

**Comment by bistline** [comment]
Green build on 6124cca at 2021.03.22 4:26pm

**Comment by bistline** [comment]
Second green build at 2021.03.24 3:32pm

**Comment by bistline** [comment]
Third green build on 5565d70 at 2021.03.25 10:22am

**Comment by bistline** [comment]
Fourth green build on 967a869 at 2021.03.25 1:58pm

**Comment by bistline** [comment]
Fifth green build on 967a869 at 2021.03.25 4:34pm

**Review by devonbush — APPROVED** [review]
Nice, I am a big fan of all these changes.  I especially like the work you did to use a detached study for testing the inferCNV stuff -- it makes the test a little more complex, but hopefully much faster and more reliable

**Review by eweitz — APPROVED** [review]

**Pull request merged**
