### PR TITLE
Fixing scatter plot legends in spatial UX (SCP-5626)

### PR DESCRIPTION
**Pull request by bistline**
#### BACKGROUND & CHANGES
This update fixes issues discovered with scatter plot legends when viewing multiple plots in the spatial UX.  Whenever a user selects a new spatial plot, every legend shown then updates the counts to use data from the newest spatial plot.  Additionally, if certain labels are missing from the newest plot, those legend entries are still shown but with a count of 0.

The cause was from a shared `useState` reference in `ExploreDisplayTabs` for setting label counts (this was done so it could be shared with various components in the differential expression UX).  Now, counts are managed at the `ScatterPlot` level instead of `ExploreDisplayTabs`.  Additionally, color assignments are now tracked using the main, non-spatial plot as the control.  Any additional spatial plots will use that color map to ensure that labels keep the same color assignment across all plots.

Note: you may see a brief flicker as colors are reassigned, this has to do with waiting for the main plot to finish rendering.

#### MANUAL TESTING
The easiest way to test this PR is to ingest data from [SCP1375](https://singlecell.broadinstitute.org/single_cell/study/SCP1375) (this is the study where the above bugs were found).  Only 4 files are needed for testing:
- [metadata.csv](https://singlecell.broadinstitute.org/single_cell/data/public/SCP1375/integrative-in-situ-mapping-of-single-cell-transcriptional-states-and-tissue-histopathology-in-an-alzheimer-disease-model?filename=metadata.csv) (Metadata file)
- [top_level_umap.csv](https://singlecell.broadinstitute.org/single_cell/data/public/SCP1375/integrative-in-situ-mapping-of-single-cell-transcriptional-states-and-tissue-histopathology-in-an-alzheimer-disease-model?filename=top_level_umap.csv) (Normal clustering)
- [spatial_8months-control-replicate_1.csv](https://singlecell.broadinstitute.org/single_cell/data/public/SCP1375/integrative-in-situ-mapping-of-single-cell-transcriptional-states-and-tissue-histopathology-in-an-alzheimer-disease-model?filename=spatial_8months-control-replicate_1.csv) (Spatial transcriptomics)
- [spatial_13months-disease-replicate_2.csv](https://singlecell.broadinstitute.org/single_cell/data/public/SCP1375/integrative-in-situ-mapping-of-single-cell-transcriptional-states-and-tissue-histopathology-in-an-alzheimer-disease-model?filename=spatial_13months-disease-replicate_2.csv) (Spatial transcriptomics)

1.  Boot all services and sign in
2. Create a new study and ingest the 4 files above, making sure to upload the last two cluster files as spatial
3. Once all clustering/metadata have ingested, go to the Explore tab for this study (click "View study" at the top left of the upload wizard)
4. Load `top_level_umap.csv` and `top_level_cell_type` as the annotation
5. In the Spatial groups menu, select `spatial_8months-control-replicate_1.csv`
6. Confirm the count for `Astro` is **6789** for `top_level_umap.csv` and **919** for `spatial_8months-control-replicate_1.csv`
7. Confirm that `spatial_8months-control-replicate_1.csv` does not have the group `LHb`, and the color for `Micro` and the remaining labels match in both plots
8. Add `spatial_13months-disease-replicate_2.csv` from the spatial groups menu
9. Confirm the count for `Astro` is **927** and that it has the `LHb` group with a count of **65** and the correct color 
10. Change the annotation multiple times (including back to a value you've already selected) and confirm that color assignments match across all plots.
    * If you select `Hide all` in the legend for the main plot then scroll to the bottom and select the last entry, this is a quick way to ensure that assignments have stayed consistent across all plots.

### CODE REVIEW

**Comment by eweitz** [comment]
The [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/9652031890/job/26621226391?pr=2070#step:6:4902) seems to be a true positive.  I'll be available after demo if you'd like to pair!

```
Total elapsed time: 25 minutes, 54 seconds

### FAILURES and ERRORS ###
*** Yarn test failures ***
  FAIL test/js/explore/differential-expression-panel.test.js (14.966 s)
      ✕ renders DE genes table (379 ms)
      ✕ renders pairwise group picker (61 ms)
  FAIL test/js/explore/differential-expression-panel.test.js (14.966 s)

*** Rails test failures ***
Exiting with code: 1
```

**Review by eweitz — COMMENTED** [review]
The [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/9652031890/job/26621226391?pr=2070#step:6:4902) seems to be a true positive.  I'll be available after demo if you'd like to pair!

```
Total elapsed time: 25 minutes, 54 seconds

### FAILURES and ERRORS ###
*** Yarn test failures ***
  FAIL test/js/explore/differential-expression-panel.test.js (14.966 s)
      ✕ renders DE genes table (379 ms)
      ✕ renders pairwise group picker (61 ms)
  FAIL test/js/explore/differential-expression-panel.test.js (14.966 s)

*** Rails test failures ***
Exiting with code: 1
```

**Comment by bistline** [comment]
> The [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/9652031890/job/26621226391?pr=2070#step:6:4902) seems to be a true positive. I'll be available after demo if you'd like to pair!
> 
> ```
> Total elapsed time: 25 minutes, 54 seconds
> 
> ### FAILURES and ERRORS ###
> *** Yarn test failures ***
>   FAIL test/js/explore/differential-expression-panel.test.js (14.966 s)
>       ✕ renders DE genes table (379 ms)
>       ✕ renders pairwise group picker (61 ms)
>   FAIL test/js/explore/differential-expression-panel.test.js (14.966 s)
> 
> *** Rails test failures ***
> Exiting with code: 1
> ```

Yeah, on it - pretty sure I know what I broke in the test.

**Comment by bistline** [comment]
Build failure now is unrelated, upstream Terra issue.

**Comment by bistline** [comment]
I just discovered a bug with this... everything works fine on initial load where you add spatial plots iteratively, but once they're all loaded it breaks on annotation switch or page reload.  This is because the spatial plots might render before the main plot, and the `refColorMap` changes after they've rendered, leading to color mismatches across or even within a plot (e.g. spatial plot has different colors for trace and legend).

**Comment by bistline** [comment]
@eweitz @jlchang this is ready for review now, I think I've get the state issue fixed.

**Review by eweitz — APPROVED** [review]
Code looks good, and manual test passed!

Robust_scatter_plot_legends_in_spatial_UX__SCP_2024-07-01

**Comment by eweitz** [comment]
I created [SCP405 on staging](https://singlecell-staging.broadinstitute.org/single_cell/study/SCP405) to reproduce SCP1375 from production, for convenient reference.

**Review by jlchang — APPROVED** [review]
Checked gene expression plotting with latest changes and manual tests all look good. Thanks for catching the coloring consistency issue during demo and finding the fix so quickly!

**Pull request merged**
