### PR TITLE
Robust IGV filtering: drag, zoom, search (SCP-5678)

### PR DESCRIPTION
**Pull request by eweitz**
This decreases brittleness in dynamic filtering in IGV tracks, maturing major new genome browser functionality.

### Overview
[Previously](https://github.com/broadinstitute/single_cell_portal_core/pull/2068), applying a filter degraded subsequent locus changes in IGV.  After filtering IGV, any change in the genomic coordinate frame -- panning / dragging, zooming, searching another gene -- did not show expected genomic features in the filtered track.

Now, such locus changes after multiome filtering work as expected.  This hardens the UX for slicing-and-dicing ATAC fragment BED files.  That in turn accelerates insights on gene expression and epigenetics.

### Demo
Here's how it looks!

https://github.com/broadinstitute/single_cell_portal_core/assets/1334561/dd93199b-4823-428a-9870-7d8e0d58f4c0

### Next steps
The UX is more robust, but some papercuts remain.  A better "loading" indication for filtered results would be smoother.  Support for [IGV filtering via URL](https://broadworkbench.atlassian.net/browse/SCP-5673) would help share chromatin accessibility insights.

### Tests
Automated tests were updated to account for this refinement.  To manually test:
1.  Go to a study that has an ATAC fragment BED file, e.g. the 3k cell PBMC 10x multiome example dataset
* Staging: https://singlecell-staging.broadinstitute.org/single_cell/study/SCP395
* Production: https://singlecell.broadinstitute.org/single_cell/study/SCP2699
2.  Search gene SPIB
3. Go to "Genome" tab
4. Click "Filter plotted cells"
5. Click root checkbox in "Atac cluster" facet, to deselect all filters
6. Click filter for "5" 
7. Confirm ATAC fragment track updates
8. Drag IGV frame to the left
9. Confirm updated ATAC fragments still appear
10. Zoom out in IGV
11. Confirm updated ATAC fragments still appear
12. In SCP gene search box, query for "ANXA1"
13. Confirm IGV updates to ANXA1, and ATAC fragments appear
14. Change filter selection
15. Confirm ATAC fragment track updates

This satisfies SCP-5678.

### CODE REVIEW

**Review by bistline — APPROVED** [review]
Looks great!  Nice work.

**Review by jlchang — CHANGES_REQUESTED** [review]
Following the functional review instructions works as expected BUT if I then click "Return to cluster view" (see video at ~40s timepoint) and try a new gene search, I get "Something went wrong". If there's a way to avoid the error, it'd be great to include in this PR.

https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/dffe8bb9-de8d-4540-a69d-3b67d53bb6ec

**Comment by eweitz** [comment]
> if I then click "Return to cluster view" (see video at ~40s timepoint) and try a new gene search, I get "Something went wrong".

Good find, Jean!  It turns out that bug is pre-existing on production and not caused by these changes.  It also requires a substantially different fix than what's in scope here.  

I've gone ahead and fixed the separate bug you found. That incidentally made URL support for IGV cell filtering much easier to implement.  Please see PR #2079 for the fix and related enhancement.

**Review by jlchang — APPROVED** [review]
Thanks for PR [2079](https://github.com/broadinstitute/single_cell_portal_core/pull/2079). Checking it out next!

**Comment by eweitz** [comment]
[Build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/9857729172/job/27217440610?pr=2075#step:6:4438) is a false positive:

```
Total elapsed time: 26 minutes, 42 seconds

### FAILURES and ERRORS ###
*** Yarn test failures ***

*** Rails test failures ***

  FireCloudClientTest#test_create_and_manage_user_groups:
  RuntimeError: Wrapped undumpable exception for: RestClient::InternalServerError: 500 Internal Server Error
Exiting with code: 1
```

**Pull request merged**
