### PR TITLE
Subsampling in explore tab no longer defaults to 'all cells' (SCP-3144)

### PR DESCRIPTION
**Pull request by devonbush**
This now defaults to the minimum subsample -- is that right?  Adding @jlchang  to the review to confirm the default and also the tooltip content (shown below)

Also added a tooltip based on our existing one 
image

### CODE REVIEW

**Comment by bistline** [comment]
@devon The default is actually 10K cells if the cluster has more than 10K, otherwise it is 'All Cells'.

**Comment by devonbush** [comment]
Just updated to match @bistline 's comment

**Comment by devonbush** [comment]
test failures are unrelated

**Review by bistline — APPROVED** [review]

**Review by jlchang — APPROVED** [review]
Thanks to Devon for the walkthrough!

**Pull request merged**
