### PR TITLE
Improve Image Pipeline scalability: use prefetched expression (SCP-4563)

### PR DESCRIPTION
**Pull request by eweitz**
This enables Image Pipeline to retrieve expression data from local files, so it processes more robustly and faster.

### Impact
[Previously](#1577), expression data for gene expression scatter plot images was fetched via SCP REST API in Image Pipeline.  This was convenient, but scaled poorly.  It entailed immense load on the SCP application and database servers -- enough so that we'd need to do something like transiently shard MongoDB, spin up infrastructure copies via Terraform, and generally do a bunch of complicated stuff in order to not take down production.  In terms of performance, that complicated approach would at best still be rather slow for studies with extremely many cells.

Now, expression data can be read from local, prefetched files.  With the forthcoming scatter data pipeline, we'll be able to generate expression data arrays for all genes and clusters in a given study _without_ hitting SCP API and all its attendant load and speed issues.  Combined with that work, this enhancement will essentially eliminate "backend" and "transfer" time.  

That [saves > 10 seconds per gene](https://mixpanel.com/project/2120588/view/19059/app/insights/#report/31338756/expression-scatter-plot-time-0-5-m-1-m-points), which with 25K genes <ins>_saves almost 3 days per Image Pipeline run_</ins> on large studies.

### Architecture
Below is a diagram showing where this fits in the upcoming architecture.  This derisks some of the "Image Pipeline" part at right -- specifically, that it can read standalone scatter data files (much of the green arrow).  Forthcoming work in Ingest Pipeline will prove we can write such scatter data.  

[](https://docs.google.com/document/d/1-mhtoWrg3RHoDjWrHGv2h-KtlnnYGPg5-lxlgRyWaK0/edit#heading=h.cg3befaxtgyj)

Future work will mature how Image Pipeline fetches scatter data from the bucket, handles file names, etc.

To test:
* Get the accession for your local "Human milk -- differential expression" study
* In Terminal, `cd image-pipeline`
* Substituting your accession, run the following command for 2 minutes, then terminate it:
`rm -rf output/; export NODE_TLS_REJECT_UNAUTHORIZED=0; time node expression-scatter-plots.js --accession="<your accession>"; tput bel; # localhost, human milk DE study`
  * If you immediately see `TypeError: fetch failed`, edit `expression-scatter-plots.js` to use `https://127.0.0.1:3000` instead of `https://localhost:3000`, then re-run above
* Confirm the following shows JSON files: `ls -latr output/<your_accession>/json/`
* Substituting your accession, run the following command for 2 minutes (or a few seconds after you see `Completed loading Explore tab` in console)
`export NODE_TLS_REJECT_UNAUTHORIZED=0; time node expression-scatter-plots.js --accession="<your accession>"; tput bel; # localhost, human milk DE study`
* While that is running, terminate your local `rails s` command and confirm the Image Pipeline script still runs
  * This can be a bit tricky, because your OS focus will be yanked back to Chromium.  Go to the terminal tab you're running `rails s` on then kill it via e.g.  `Ctrl + c`.

This satisfies SCP-4563.

### CODE REVIEW

**Comment by eweitz** [comment]
I've converted this to a draft while I investigate an issue others are having reproducing the test steps locally.  Jon just encountered the [same error that Emily had on 8/2](https://github.com/broadinstitute/single_cell_portal_core/pull/1577#pullrequestreview-1059382085).

Jon's case:

```
image-pipeline % rm -rf output/; export NODE_TLS_REJECT_UNAUTHORIZED=0; time node expression-scatter-plots.js --accession="SCP66"; tput bel
Number of CPUs to be used on this client: 1
Accession: SCP66
Fetching https://localhost:3000/single_cell/api/v1/studies/SCP66/explore
(node:34875) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34875) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.node:internal/deps/undici/undici:6254
          p.reject(Object.assign(new TypeError("fetch failed"), { cause: response.error }));
                                 ^

TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:6254:34)
    at node:internal/deps/undici/undici:6579:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: connect ECONNREFUSED ::1:3000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1246:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3000
  }
}

Node.js v18.6.0
```

**Review by bistline — APPROVED** [review]
Using the workaround of `127.0.0.1` instead of `localhost` worked, and I validated it does in fact read the local file, if present.

**Comment by eweitz** [comment]
Good find, Jon -- thanks.  I've updated the test instructions to note that workaround and iron out some other wrinkles.

For any others doing functional review: the 127.0.0.1 workaround yields images that are cropped poorly, but confirms the essential update here of being able to read local expression array data (similar to that generated by [scp-ingest-pipeline #269](https://github.com/broadinstitute/scp-ingest-pipeline/pull/269)) and produce a gene expression scatter plot.

**Review by ehanna4 — COMMENTED** [review]
Strangely this time `localhost` does work for me. However, if I kill the Rails server it also breaks the script with the `TypeError: fetch failed`. I cannot get this to run using the `127.0.0.1` workaround at all

**Review by ehanna4 — APPROVED** [review]
Paired with Eric, and realized was not following testing steps totally accurately so trying again and following exactly got it working👍

**Comment by eweitz** [comment]
The [build failure](https://github.com/broadinstitute/single_cell_portal_core/runs/8081305710?check_suite_focus=true#step:5:4036) is the same false positive that's been flaking CI lately:

```
Total elapsed time: 24 minutes, 41 seconds

### FAILURES and ERRORS ###
*** Yarn test failures ***

*** Rails test failures ***

  SearchFacetTest#test_should_find_all_filter_matches [/home/app/webapp/test/models/search_facet_test.rb:226]:
Exiting with code: 1
```

Per [comments in other PRs](https://github.com/broadinstitute/single_cell_portal_core/pull/1600#issuecomment-1230841138), that's addressed in #1598.

**Pull request merged**
