### PR TITLE
Yr plotly violins

### PR DESCRIPTION
**Pull request by YanayRosen**
Replacing custom implementation of violin plots with Plotly's implementation.

### CODE REVIEW

**Comment by YanayRosen** [comment]
I added a jstat dependency and js for stats-- when we merge with the branch that has the extended morpheus package we can get rid of this.

**Comment by eweitz** [comment]
Looks good to me as well.  The updated violin plots look good on my local machine, and code style is consistent with what we have in place.  Kudos, Yanay!

**Comment by eweitz** [comment]
I'll defer to @bistline on final review and merge.

**Comment by bistline** [comment]
So we found a problem with data that essentially has no distribution:

screen shot 2018-06-15 at 3 47 50 pm

In this instance, we should plot nothing, or just a standard box, if the violin is going to be misleading.

**Pull request merged**
