### PR TITLE
Fixing bugs with launching DE jobs on sparse matrices (SCP-4196)

### PR DESCRIPTION
**Pull request by bistline**
This update addresses bugs in launching differential expression jobs using MTX sparse matrices.  It also adds an integration test to validate that this functionality works for both dense and sparse matrices.

MANUAL TESTING
There are two ways to test this manually.  The simplest is to run the integration test via `bin/rails test test/integration/lib/differential_expression_service_test.rb -n /sparse/` and confirm that it passes:
```
Run options: -n /sparse/ --seed 6351

# Running:

SUITE DifferentialExpressionServiceTest starting
differential_expression_service_test.rb:94 test_should_run_differential_expression_job_with_sparse_matrix starting
differential_expression_service_test.rb:94 test_should_run_differential_expression_job_with_sparse_matrix completed (6.585 sec)
.DifferentialExpressionServiceTest: Cleaning up 2 studies, 1 users
SUITE DifferentialExpressionServiceTest completed (17.734 sec)
```
Or, you can test manually with these steps:
1. Boot as normal and start DelayedJob
2. Download the sample sparse data from [scp-ingest-pipeline](https://github.com/broadinstitute/scp-ingest-pipeline/tree/development/tests/data/differential_expression/sparse) and upload the raw matrix (and associated files), clustering, and metadata files to a new study
3. Once all files are ingested, run a differential expression job in the rails console and validate that it returns `true`:
```
DifferentialExpressionService.run_differential_expression_on_default(<accession of above study>)
```

This update further supports SCP-4196.

### CODE REVIEW

**Review by devonbush — APPROVED** [review]

**Review by jlchang — COMMENTED** [review]
I replicated a production study locally and was able to "run a differential expression job in the rails console and validate that it returns true" AND saw pipelines worker running for a while BUT did not end up with any DE output files in the bucket for the local study... Should I have expected to get output?

**Review by jlchang — CHANGES_REQUESTED** [review]
Cluster names in studies are allowed to have spaces and non-alphanumeric characters. The value for the --cluster-name parameter needs to be quoted for DE jobs to run correctly. I tried running DE on a study I replicated locally that had cluster name `BC-P1 (CID4471)` and the DE job failed (see comment).

Please modify ingest job submission so that unusual cluster names are successfully passed to ingest_pipeline.py.

CORRECTION: the call to ingest pipeline by rails was fine (I had the wrong docker image specified in my local instance).

**Comment by bistline** [comment]
> Cluster names in studies are allowed to have spaces and non-alphanumeric characters. The value for the --cluster-name parameter needs to be quoted for DE jobs to run correctly. I tried running DE on a study I replicated locally that had cluster name `BC-P1 (CID4471)` and the DE job failed (see comment).
> 
> Please modify ingest job submission so that unusual cluster names are successfully passed to ingest_pipeline.py.

Ah great catch - thanks!

**Review by eweitz — APPROVED** [review]

**Comment by eweitz** [comment]
I'll go ahead and merge this, per chat with Jon earlier today about avoiding a GitHub Actions bug seen with hotfixes.

**Pull request merged**
