### PR TITLE
Primary Human Data must have human as species (SCP-4030)

### PR DESCRIPTION
**Pull request by ehanna4**
If the file has been indicated to be a Primary Human Data sequence file the species should be human. Previously the user would be able to change the species even when having selected this. This will fix it so that a user cannot change the species when the Primary Human Data option has been selected. Please note a user is able to have the species be a human without having chosen the Primary Human Data.

Current/Previous Behavior:
Screen Shot 2022-01-25 at 1 57 31 PM

To test:
- Pull this branch
- go to the wizard to the sequence file upload section
- click back and forth between Yes and No on the Primary Human Data option and try changing the species

Video showing the new behavior plus printing the value in the "selectedSpecies" variable
https://user-images.githubusercontent.com/54322292/151044228-f6f58f43-8aa1-4dc3-8973-8fc03729ab8a.mov

### CODE REVIEW

**Comment by ehanna4** [comment]
https://user-images.githubusercontent.com/54322292/151044481-226c9b2f-3e5e-44a1-8b03-3084bc736d98.mov

**Review by devonbush — APPROVED** [review]
Nicely done!

**Review by bistline — APPROVED** [review]

**Review by eweitz — COMMENTED** [review]
Code looks good!  

Is this also relevant for sync?

**Comment by ehanna4** [comment]
> Code looks good!
> 
> Is this also relevant for sync?

I don't know, I believe this behavior had existed in the previous wizard we just missed bringing it to the new one, so since sync wasn't changed if it was there it should still be there and if not we can add it with the new update :)

**Review by eweitz — APPROVED** [review]

**Pull request merged**
