### PR TITLE
Upgrading to rails-baseimage:2.3.0, Ruby 3.2, Nodejs 20, Vite 4

### PR DESCRIPTION
**Pull request by bistline**
#### BACKGROUND & CHANGES
This updates to the latest release of `singlecellportal/rails-baseimage`, which updates to Ruby 3.2.2 and Nodejs 20.  Additionally, this updates to Vite 4.5.  It also removes a deprecated gem (`ruby-prof-flamegraph`) that no longer builds past Ruby 3.1.

EDIT: CI will not run on this PR until the [associated upstream PR](https://github.com/broadinstitute/scp-rails-baseimage/pull/29) to update the base image merges.

#### MANUAL TESTING
Given the headaches I went through to manually validate that this works in Docker, I highly recommend that you _not_ do this, especially since we do not develop in Docker locally as part of normal workflows.  There is a bug in Docker Desktop for Mac prior to v4.30 that results in segmentation faults for Vite, and additionally there's a lot of manual shenanigans required to include the required Docker images as they haven't been published yet.  Also, it is not possible to deploy different Docker image tags to staging, so this also cannot be done there.  The underlying scripts accept the arguments, but the Github Action workflows do not allow you to specify them.

Instead, I would validate that the normal non-Dockerized setup still functions:

1. Install Nodejs 20 via nvm:
```
nvm install 20.13.0
...
$ node -v                                                                                       
v20.13.0
```
2. Install Ruby 3.2.2 locally using your manager of choice (this will take a while!)
EDIT: If you have an Apple Silicon Mac and encounter issues installing Ruby 3.2.2, see this thread: https://github.com/rbenv/ruby-build/discussions/2293
Specifically, `MAKE_OPTS='-j2' rbenv install 3.2.2` may solve compiler issues preventing installation.  You may also have to re-install Xcode and the command line tools after requesting an administrator session:
```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
# wait for a while, click stuff
sudo xcode-select -s /Library/Developer/CommandLineTools
```
Then to install Ruby 3.2.2:
```
# rvm
rvm get stable
rvm install 3.2.2

# rbenv
brew update && brew upgrade ruby-build 
rbenv install 3.2.2
```
3. Make sure that you have the correct version of Ruby loaded in your shell:
```
# rvm
rvm use 3.2.2

# rbenv
rbenv shell 3.2.2

...
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin23]
```
4. Pull this branch and install necessary gems/packages
```
bundle install
yarn install
```
5. Boot the server & vite as normal and confirm everything loads (make sure the vite shell has the right node/ruby loaded as well).

### CODE REVIEW

**Review by eweitz — APPROVED** [review]
Code looks good, manual test worked.  

Thanks for helping spelunk a solution for Apple silicon!

**Comment by eweitz** [comment]
The [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/9022800260/job/24793183555?pr=2036#step:4:137) looks like a true positive:

```
#### CHANGES DETECTED TO DOCKERFILE, REBUILDING IMAGE LOCALLY ####
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  114.9MB

Step 1/23 : FROM gcr.io/broad-singlecellportal-staging/rails-baseimage:2.3.0
manifest for gcr.io/broad-singlecellportal-staging/rails-baseimage:2.3.0 not found: manifest unknown: Failed to fetch "2.3.0" from request "/v2/broad-singlecellportal-staging/rails-baseimage/manifests/2.3.0".
```

**Comment by bahill** [comment]
Looks like the tests didn't run?
https://github.com/broadinstitute/single_cell_portal_core/actions/runs/9022800260/job/24793183555?pr=2036

Also - do you want/need my review on this?

**Comment by bistline** [comment]
@eweitz as noted the tests won't run until [this PR](https://github.com/broadinstitute/single_cell_portal_core/pull/2036) merges.  And no @bahill you don't need to review this one - it's reliant on a local development environment so there's not really any way for you to test it out.

**Review by jlchang — APPROVED** [review]
Manual test passed (thanks for troubleshooting the SSL issue, Jon!)

All good.

**Pull request merged**
