### PR TITLE
Gene search analytics and UX fixes (SCP-3147)

### PR DESCRIPTION
**Pull request by devonbush**
This has a quick-and-dirty fix for handling too many genes in the bar
image
The scrollbar isn't great, but it's better than the previous behavior of overflowing into the graphs (and arguably no worse than the current too-small text field)
image

This also improves handling of copy-pasted gene lists into the bar, as well as giving even more detail on events

To test:
1. open a study with react_explore feature flag enabled
2. paste a list of genes into the search bar (e.g. "foo bar baz") and then hit enter/tab/space
3. Observe the genes get divided appropriately
4. Add a lot of genes, and observe that a vertical scrollbar appears to scroll, rather than overflow

### CODE REVIEW

**Comment by devonbush** [comment]
This is now updated to reflect Eric's comments in the (now closed) PR https://github.com/broadinstitute/single_cell_portal_core/pull/925

**Review by eweitz — CHANGES_REQUESTED** [review]
Thanks for including screenshots -- very helpful.  And kudos on the analytics refinement.  I think it nicely addresses this use case.

Overflowing via scrollbar is better than graphically overflowing the container, but the scrollbar will definitely frustrate users.  [One in five gene searches involve >= 10 genes](https://docs.google.com/document/d/1FBQpUBJ0H51dNCeBUM-qN3fY1AM4nleI8HFdfHoVDC8/edit#heading=h.pypfnu913fxu), so I think a reasonable solution needs to be not only not-broken (as you've achieved here) but also not frustrating.

The [React Select docs](https://react-select.com/home) give an example of nicely handling overflow.  

Please implement that here, or open a ticket for next sprint to polish multiselect overflow UX.

Also, SCP-3147 notes "For spatial, we should implement paging controls".  Is a separate ticket needed for that?

**Review by bistline — CHANGES_REQUESTED** [review]
I agree with Eric that the vertical scrollbar will be both difficult to see and use.  I think we should investigate a different option.  The analytics updates are good to go.

**Comment by devonbush** [comment]
https://broadworkbench.atlassian.net/browse/SCP-3169 covers UX improvement for this feature -- quick-and-dirty-but-instrumented was the goal here

**Review by eweitz — APPROVED** [review]
Thanks for creating the follow-up!  This works for now.

We'll also want to fix the backwards-incompatibility of these gene search analytics, e.g. so it uses an event named `search` with properties like `context`, `scope`, `numGenes`.  There are also existing analytics on how users interact with gene search -- e.g. whether it's triggered via click on the icon, "enter" key, or via related genes ideogram.

Assuming that analytics issue gets fixed here or ticketed for next sprint prep, I approve.

**Review by bistline — APPROVED** [review]

**Comment by devonbush** [comment]
test failures unrelated

**Pull request merged**
