### PR TITLE
Log file validation trigger to Mixpanel (SCP-3704)

### PR DESCRIPTION
**Pull request by bistline**
This update adds the `trigger` property to all Mixpanel `file-validation` events.  This will enable admins to ascertain which view/page a file validation event was triggered from (currently, the upload wizard or the sync page).  This information will be useful for determining next steps for extending client-side validation to other parts of the application.

MANUAL TESTING
1. Boot as normal and sign in
2. Create a new study, or go to the upload wizard for an existing study
3. Open the network tab in Chrome Dev Tools
4. Click into the `Clustering` section of the upload wizard, and upload `cluster_bad_no_coordinates.txt` from `test/test_data/validation`
5. Find the `file-validation` event in the Network tab, and confirm that the `trigger` property is set to `upload` as seen below:
Screen Shot 2022-01-18 at 4 19 33 PM

This PR satisfies SCP-3704.

### CODE REVIEW

**Review by eweitz — APPROVED** [review]
Short and sweet!  

You and I had discussed how deferring implementation of the `cli` trigger made sense, given it'd require delving into a rarely-touched codebase for something that's rarely-used.  

Considering further, `cli` seems more appropriate for another property.  Like this SCP GUI, the SCP CLI _also_ has "upload" and "sync" validation (or ought to), and so the complementary upcoming `logger` property -- not this `trigger` property -- seems best to distinguish GUI vs. CLI.  

So using `trigger` and `logger` would give us "trigger: upload, logger: gui", "sync gui", "upload cli", and "sync cli".  (Of course neither of those sync CSFV contexts are implemented yet, with the latter not even roadmapped.)

**Comment by bistline** [comment]
> Considering further, `cli` seems more appropriate for another property. Like this SCP GUI, the SCP CLI _also_ has "upload" and "sync" validation (or ought to), and so the complementary upcoming `logger` property -- not this `trigger` property -- seems best to distinguish GUI vs. CLI.
> 
> Using `trigger` and `logger` would give us "trigger: upload, logger: gui", "sync gui", "upload cli", and "sync cli". (Of course neither of those sync CSFV contexts are implemented yet, with the latter not even roadmapped.)

I like where you're going with that - and I agree.  I think the two fields combined would give us the most accurate picture.  Personally, I would prefer `client` over `logger` as it seems more apposite, but I'm not sure if that will conflict with an existing property in Mixpanel (it doesn't look like it, but it is also an over-used term).

**Review by devonbush — APPROVED** [review]
Approving because it satisfies the ticket definition.  But I think what you've got here is much more generally useful.  Consider:
rename `getValidationTrigger` to `getUserReadablePageName()`, and have it just return the analyticsPageName if none of the ifs are true
rename `trigger` in `getLogProps` to something like `readablePageName`

**Comment by devonbush** [comment]
'Trigger' has the difficulty that the scope is unclear.  In the context of an event, is the 'trigger' which button they clicked, which page they were on, or which app they were using? So I lean towards using a property name that's more descriptive about what it is, and then let mixpanel reports be the ones to assign meaning like 'trigger'

**Comment by bistline** [comment]
> 'Trigger' has the difficulty that the scope is unclear. In the context of an event, is the 'trigger' which button they clicked, which page they were on, or which app they were using? So I lean towards using a property name that's more descriptive about what it is, and then let mixpanel reports be the ones to assign meaning like 'trigger'

@devonbush @eweitz I'm not sure how to proceed now given these comments.  Are further changes needed?  There doesn't seem to be consensus on what to call things.  I would opt to leave things as-is as it satisfies the specific AC for the ticket, but there seems to be differing opinions now.

**Comment by eweitz** [comment]
Per chat among participants here, we’ve got rough consensus to merge, and maybe a possible retro / engineering strategy topic to discuss the reasonable non-blocking concerns that have been raised.

**Pull request merged**
