### PR TITLE
AnalysisSubmission bug fixes & refinements

### PR DESCRIPTION
**Pull request by bistline**
* Sorts submissions by creation date on report export 
* Bugfixes:
  * fixes references to non-existent users in error handling
  * adding begin/rescue block to allow migration to complete due to missing configurations

### CODE REVIEW

**Comment by eweitz** [comment]
The failing CI build seems worth a look: 
https://travis-ci.com/broadinstitute/single_cell_portal_core/builds/109176937#L3022

**Comment by bistline** [comment]
> The failing CI build seems worth a look:
> https://travis-ci.com/broadinstitute/single_cell_portal_core/builds/109176937#L3022

That may be a red herring - there were some spotty outages around then.  I'm re-running the build to make sure.  I didn't change any of that code, so if the test fails again, then I'll look into it, but it should pass.

**Comment by bistline** [comment]
It was a red herring - the build passed this time.

**Comment by bistline** [comment]
didn't mean to close this PR

**Pull request merged**
