### PR TITLE
Handle docker cleanup for development tag (SCP-4551)

### PR DESCRIPTION
**Pull request by bistline**
#### BACKGROUND & CHANGES
#1623 introduced logic to automatically clean up any obsolete/unused Docker artifacts after successful deployments.  However, in the staging environment, all Docker images are tagged with `development`, which caused [problems](https://scp-jenkins.dsp-techops.broadinstitute.org/job/scp-deploy-development-to-staging/830/console
) when trying to run the automated cleanups.  This update skips the manual image removal portion of the cleanup as `docker image prune` will handle removing any recently untagged image layers.  In addition, this update addresses issues with the difference in behavior between `zsh` and `bash` by standardizing the `prune_docker_artifacts` method to only operate in `bash` as this is what the default shell is on our deployed hosts.  Lastly, this also fixes issues with source/imports in `bash` when testing locally.

#### MANUAL TESTING
1. Pull branch and navigate to the `bin` directory in project source
2. Pull the `development` tag via `docker pull gcr.io/broad-singlecellportal-staging/single-cell-portal:development`
3. Run `source docker_utils.sh` and confirm you get no errors
4. Determine what your shell is by running `echo $SHELL`
    * If you are running `zsh`, confirm that the script exits correctly by running step 4 and seeing the message `zsh detected, exiting as this function only operates on bash shells`
    * Next, run the following code to enter and configure a `bash` session:
    ```
    bash
    SHELL=/bin/bash
    source docker_utils.sh
    ```
5. Run `prune_docker_artifacts "gcr.io/broad-singlecellportal-staging/single-cell-portal" "development"` (note we are passing in an image tag now, which will be passed to `remote_deploy.sh` during a deployment by Jenkins)
6. Note the following message in the console:
```
% prune_docker_artifacts "gcr.io/broad-singlecellportal-staging/single-cell-portal" "development"
Skipping manual image cleanup of gcr.io/broad-singlecellportal-staging/single-cell-portal:development; not enough versions present
pruning orphaned image layers
...
```

### CODE REVIEW

**Review by eweitz — COMMENTED** [review]
This errors at least with `bash`:
```
wm10d-4e7:bin eweitz$ source docker_utils.sh
dirname: illegal option -- b
usage: dirname string [...]
```

Like we supported both `zsh` and `bash` in #1625, I imagine we also want to here.

**Comment by bistline** [comment]
> dirname: illegal option -- b

Since this file is always used as an import, and not directly, I'm not concerned by this.  We don't have to support usage directly anywhere - that's simply for testing.  If you want to get around that error, you can edit `bin/docker_utils.sh` line 3 to read like this:

```
THIS_DIR="$(cd "$(dirname -- "$0")"; pwd)"
```

**Review by eweitz — APPROVED** [review]
Code looks good!  (See notes above regarding functional test.)

**Review by jlchang — COMMENTED** [review]
Functional review: inconclusive
When I tried to source `docker_utils.sh `, I got an error message:

> ~/Documents/GitHub/single_cell_portal_core/bin (jb-docker-cleanup-development) $ 
> source docker_utils.sh
> dirname: illegal option -- b
> usage: dirname string [...]
> RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
> you can ignore these warnings with 'rvm rvmrc warning ignore /Users/jlchang/Documents/GitHub/single_cell_portal_core/Gemfile'.
> To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.
> 
> 
> Saving session...completed.

But there did seem to be a `prune_docker_artifacts` function in the environment so I tried running the cleanup script to realize I had no images to prune...

> ~/Documents/GitHub/single_cell_portal_core/bin (jb-docker-cleanup-development) $ prune_docker_artifacts "gcr.io/broad-singlecellportal-staging/single-cell-portal" "development"
> Current tag is development, skipping manual image cleanup of gcr.io/broad-singlecellportal-staging/single-cell-portal
> pruning orphaned image layers
> Total reclaimed space: 0B
> pruning orphaned volumes
> Total reclaimed space: 0B

Before I try to load up my laptop with images, did sourcing `docker_utils.sh` work properly?

**Comment by bistline** [comment]
There is more to do on this PR as was seen in the recent deployment - will update when I have a more robust solution for the `bash` issues.

**Review by eweitz — APPROVED** [review]

**Review by ehanna4 — COMMENTED** [review]
Up to step 4 works as expected:
`ehanna@wm182-ba7 bin % prune_docker_artifacts "gcr.io/broad-singlecellportal-staging/single-cell-portal" "development"
zsh detected, exiting as this function only operates on bash shells`

however after switching to bash i get this:
`bash-3.2$ prune_docker_artifacts "gcr.io/broad-singlecellportal-staging/single-cell-portal" "development"
bash: prune_docker_artifacts: command not found`

**Comment by bistline** [comment]
> however after switching to bash i get this:
> 
> ```
> > bash-3.2$ prune_docker_artifacts "gcr.io/broad-singlecellportal-staging/single-cell-portal" "development"
> > 
> > bash: prune_docker_artifacts: command not found
> ```

Did you reload it when entering `bash` with `source docker_utils.sh`?  You're technically in a new shell session so it won't load anything from the `zsh` shell.

**Review by ehanna4 — APPROVED** [review]
Functional review only - Running through the test steps a second time I was successful in seeing the final output messages as described

**Pull request merged**
