### PR TITLE
Skip reporting user group errors re: terms of service compliance (SCP-5469)

### PR DESCRIPTION
**Pull request by bistline**
#### BACKGROUND && CHANGES

This update prevents reporting errors upstream to Sentry related to checking an authenticated user's Terra user groups when that user is not in compliance with the terms of service.  These API calls return a `401`, which is not actionable on the part of SCP, and results in needless error reports in Sentry.  Also, since these calls can originate from many different codepaths, multiple different error classes are created in Sentry that all originate from the same API call.  Since it does not have a user-facing component (that is handled separately upon sign-in and asynchronously on page loads), silencing these errors makes the most sense.

Most of the changes in this PR are linting updates regarding calling `.freeze` on constants, but the one functional change is at `fire_cloud_client.rb`, line 32:

```
ERROR_IGNORE_LIST = [
  "#{BASE_URL}/register", "#{BASE_URL}/api/groups", "#{BASE_SAM_SERVICE_URL}/api/termsOfService/v1/user/self"
].freeze
``` 

This adds the necessary API endpoints to the list of calls to not report errors upstream to Sentry.

#### MANUAL TESTING
This manual test requires a user account that is both registered for Terra and not in compliance with the current terms of service.  If you do not have access to one, please refer to [this document](https://docs.google.com/document/d/1QslqdIN0o7OCQ_bNY9YFvVgU6v_JtdQqnV4i33BwakQ/edit) for access to the test account `single.cell.user1@gmail.com` as this account meets the testing criteria.
1. Boot as normal
2. Sign in with the account that is not in compliance
3. In a separate Rails console session, load the same user account:
```
user = User.find_by(email: '<email of above account>')
```
4. Create a `FireCloudClient` instance using this account and attempt to load its user groups:
```
client = FireCloudClient.new(user:)
client.get_user_groups
```
5. Open `development.log` and look for the following message (the ID will be different but the content is the same)
```
FireCloud API request (GET) https://api.firecloud.org/api/groups with tracking identifier: 647752ef94ec8fcad94deb7b
401 Unauthorized: {"causes":[{"causes":[],"message":"User must accept the latest terms of service. Please go to app.terra.bio to accept the latest terms of service.","source":"sam","stackTrace":[],"statusCode":401}],"message":"User must accept the latest terms of service. Please go to app.terra.bio to accept the latest terms of service.","source":"Sam","stackTrace":[],"statusCode":401};  encountered when requesting 'https://api.firecloud.org/api/groups', attempt #1
Retry count exceeded when requesting 'https://api.firecloud.org/api/groups' - User must accept the latest terms of service. Please go to app.terra.bio to accept the latest terms of service.
```
6. Note that there is no related message stating `Suppressing error reporting to Sentry: `

### CODE REVIEW

**Review by eweitz — APPROVED** [review]
Code looks good!  Looking forward to improved signal-to-noise in Sentry.

**Comment by eweitz** [comment]
The [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/7388592644/job/20099734542?pr=1961#step:5:4368) looks like a false positive.  

We've seen [similar Azul errors](https://github.com/search?q=repo%3Abroadinstitute%2Fsingle_cell_portal_core+test_should_get_HCA_metadata_tsv_link+&type=pullrequests) before, although I didn't see a failure in the expected 302-status (i.e., redirect) response.

```
### FAILURES and ERRORS ###
*** Yarn test failures ***

*** Rails test failures ***

  DeleteQueueJobTest#test_should_destroy_differential_expression_results_on_file_deletion:
  Mongoid::Errors::Validations: 

  HcaAzulClientTest#test_should_get_HCA_metadata_tsv_link [/home/app/webapp/test/integration/external/hca_azul_client_test.rb:170]:
  Expected: 302
Exiting with code: 1
Error: Process completed with exit code 1.
```

**Comment by bistline** [comment]
> The [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/7388592644/job/20099734542?pr=1961#step:5:4366) looks like a false positive.
> 
> We've seen [similar Azul errors](https://github.com/search?q=repo%3Abroadinstitute%2Fsingle_cell_portal_core+test_should_get_HCA_metadata_tsv_link+&type=pullrequests) before, although I didn't see a failure in the expected 302-status (i.e., redirect) response.
> 
> ```
> Total elapsed time: 32 minutes, 12 seconds
> 
> ### FAILURES and ERRORS ###
> *** Yarn test failures ***
> 
> *** Rails test failures ***
> 
>   DeleteQueueJobTest#test_should_destroy_differential_expression_results_on_file_deletion:
>   Mongoid::Errors::Validations: 
> 
>   HcaAzulClientTest#test_should_get_HCA_metadata_tsv_link [/home/app/webapp/test/integration/external/hca_azul_client_test.rb:170]:
>   Expected: 302
> Exiting with code: 1
> ```

Yeah CI is a little flaky today - I saw a similar failure after a merge to development.

**Review by jlchang — APPROVED** [review]
Functional review - works as described.

**Pull request merged**
