### PR TITLE
Show "Explore" tab by default, to ease feature discovery (SCP-5020)

### PR DESCRIPTION
**Pull request by eweitz**
This shows the Explore tab by default, if applicable, making it easier to start using the page's main features.

Previously, the Summary tab was the default.  That gave users an abstract of the study, assuming the study owners provided it.  Results of our first A/B test, enabled by #1727, showed users engage more when they land on the Explore tab by default.  Based on that, this makes the Explore tab the default landing page for all studies and all users -- as long as the study has visualizations initialized.

Before:

Explore_tab_default_before__SCP_2023-05-18

After:

Explore_tab_default_after__SCP_2023-05-18

To test:
* Go to a study that has visualizations initialized
* Confirm it shows visualizations by default

This satisfies SCP-5020.

### CODE REVIEW

**Review by bistline — APPROVED** [review]

**Comment by bistline** [comment]
Build failure looks like an Azul blip.

**Review by ehanna4 — APPROVED** [review]
Nice!

**Comment by ehanna4** [comment]
Oh wait this might need to be behind the feature flag `show_explore_tab_ux_updates`, discussing in grooming, will update this comment with more info after, but I guess hold for now probably!

**Comment by eweitz** [comment]
As Jon notes, the [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/5014274677/jobs/8988326862?pr=1780#step:7:4320) indeed seems like a false positive.  To make these easier to search and analyze in the future, here are surfaced failure diagnostics:

```
### FAILURES and ERRORS ###
*** Yarn test failures ***

*** Rails test failures ***

  HcaAzulClientTest#test_should_get_HCA_metadata_tsv_link [/home/app/webapp/test/integration/external/hca_azul_client_test.rb:180]:
Exiting with code: 1
```

**Pull request merged**
