### PR TITLE
Enrich diagrams, onboarding in related genes ideogram (SCP-5186)

### PR DESCRIPTION
**Pull request by eweitz**
This adds topology and signal peptides to protein diagrams, makes the legend interactive, and refines tooltips.

Here's how it looks!

https://github.com/broadinstitute/single_cell_portal_core/assets/1334561/2fc8c179-4b25-4574-ae8b-cc751c6c5e25

The goal is to help users discover genes, which the user then explores more fully in expression scatter plots and violin plots.  Specifically, these changes further help users learn about gene function and the degree of similarity between searched genes and related genes.  Having this conveniently in the app lets the user maintain flow.  Below are details on what's depicted in the video and how it relates to that goal.  

## Diagram improvements
Beyond deepening per below, RNA and protein diagram support is also wider.  Diagrams are shown for human _and_ mouse.

### Clearer basic features
Previously, protein diagrams showed "features" -- i.e. named 1D coordinate ranges -- from all member databases in InterPro. This made the diagrams maximally sequence-feature-rich, but also muddled them. The same features from Pfam, SMART, and other protein databases would often closely overlap. The end result was "fuzzy" protein diagrams.

Now, the diagrams show features from only the Pfam database.  (Pfam is the most comprehensive member database, and is hosted by InterPro and made available via Ensembl BioMart.)  The graphics now more clearly correspond to protein sequence diagrams in scientific illustrations.

### Topology and signal peptides
New topology and signal peptides enrich the granular functional insight provided by protein diagrams.  These protein sequence diagrams help form and refine hypotheses about the searched gene, and how other genes relate to it.  Such context augments exploration of study-specific gene expression.

For example, it's useful to see when a gene encodes a _membrane_ protein.  These are often targeted by pharmaceutical drugs, yet are underrepresented among protein structure databases.  In lieu of such 3D data -- or as an easier complement to it -- simpler 1D protein annotations for topological features and signal peptides can show glanceable fine details on a protein's typical subcellular location.

These new features reveal which proteins typically get trafficked to the outer cell membrane, or even an organelle membrane.  Topology features further show which _parts_ of the protein end up outside the cell (extracellular), inside the cell (cytosolic), or anchored in the membrane (transmembrane).  Signal peptides get cleaved off the protein en route to the protein's final destination; when these features exist, they appear at the start of the protein.  

## Onboarding refinements
Users sometimes wonder what "Interacting genes" means, or where related genes ideogram data is from.  Now, brief definitions and provenance can be found in tooltips shown upon hovering over entries in the legend at left.  The same gesture updates Ideogram to show only genes of that type.  This helps overview gene names for e.g. paralogs when there are many related genes.

Finally, per prior feedback, tooltips inside the diagrams now appear instantly on hover, rather than the default ~2 seconds.

## Test
To manually test this:
* In your terminal, stop Rails and Vite, then `yarn install --force`, then start Rails and Vite 
* Load a study with a representative set of real human genes 
* Search for a gene, like LDLR, GAD2, MTOR, PTEN, etc.
* Hover over the searched gene in related genes ideogram
* Confirm RNA and protein diagrams appear in popover
* Hover over diagrams, confirm scissors icon appears
* Hover over scissors icon, confirm tooltip shows quickly
* In "Related genes" legend, hover over legend entries for "Interacting genes" and "Paralogous genes"
* Confirm ideogram filters annotations to show only the hovered kind, while moused over the respective entry
* Confirm tooltips display for those two legend entries
* Load a study with a representative set of real mouse genes
* Search for a gene, like Ldlr, Gad2, Mtor, Pten, etc.
* Hover over the searched gene in related genes ideogram
* Confirm RNA and protein diagrams appear in popover

This upstream enhancement from Ideogram.js was integrated as part of Developer Choice Days.  It relates to SCP-5186.

### CODE REVIEW

**Review by bistline — APPROVED** [review]
Very nice - the hover behavior especially is a big usability improvement.

**Review by ehanna4 — APPROVED** [review]
Overall looks great! I note one small issue from Axe Dev tools.

Running the PR branch locally I ran it through Axe Dev tools and it is complaining about a `div` inside a list stating ["ul and ol must only directly contain li, script or template elements"](https://dequeuniversity.com/rules/axe/4.7/list?application=AxeChrome). See screenshot for better clarity on the element in question
Screenshot 2023-08-14 at 2 31 27 PM


I tested out swapping the `div` to an `li` and it looked pretty much the same so hopefully would be a small lift to fix.

**Comment by eweitz** [comment]
Nice refinement, Emily -- done in 698f5fb.  I also fixed an upstream issue and client configuration issue I found in testing.

**Comment by eweitz** [comment]
The [build failure](https://github.com/broadinstitute/single_cell_portal_core/actions/runs/5925902370/job/16066266804#step:5:3660) was a false positive: a Ruby test failed, but no Ruby code changed.

```
Total elapsed time: 51 minutes, 18 seconds

### FAILURES and ERRORS ###
*** Yarn test failures ***

*** Rails test failures ***

  StudyCreationTest#test_create_default_testing_study:
  RuntimeError: not a redirect! 200 OK

  StudiesControllerTest#test_should_create_and_then_sync_study:
  RuntimeError: Wrapped undumpable exception for: RestClient::Conflict: 409 Conflict
Exiting with code: 1
Error: Process completed with exit code 1.
```

This [seems](https://github.com/search?q=repo%3Abroadinstitute%2Fsingle_cell_portal_core+409+Conflict&type=code) caused by a Terra / FireCloud workspace already being taken.  We don't have any searchable cases of this particular false positive occurring before.

**Pull request merged**
